### PR TITLE
Use the "id" attribute in <a> tags for markdown table links.

### PR DESCRIPTION
**Pull request by EatingW**

### CODE REVIEW

**Comment by EatingW** [comment]
I don't think I can see the buildkite failures... Could someone either give me access to the buildkite results, or let me know what's wrong with the checks? Thanks!

**Comment by j3parker** [comment]
I can't give you the access (I'm just a random community member) but here is the error:

```
stardoc/BUILD:7: load-on-top: Load statements should be at the top of the file.
stardoc/BUILD:8: load-on-top: Load statements should be at the top of the file.
stardoc/BUILD:9: load-on-top: Load statements should be at the top of the file.
```

**Comment by EatingW** [comment]
Thanks for the error message! It looks like the error has nothing to do with the current pull request.

Created https://github.com/bazelbuild/stardoc/pull/50 to fix the error.

**Comment by j3parker** [comment]
I reran your build but it doesn't merge master prior to building. If you rebase it should run again automatically and pass.

**Comment by EatingW** [comment]
Right, rebase, thanks for the reminder! I think I did something wrong that forced me to have to do a force-push, but the end result seems correct.

**Comment by brandjon** [comment]
Thanks for the PR Yiting and sorry for the delay. To give an update on stardoc:

We intend to develop a replacement for stardoc that's built into the Bazel binary. This will avoid skew between a bzl file's true semantics and what the doc tooling thinks the semantics should be. When it's ready, we'll deprecate this repo.

In the meantime, we commit to keeping the essential functionality working, but will not necessarily have the bandwidth to accept enhancements. We'll be making a triage pass over this repo soon and will let you know whether we can merge this PR.

@googlebot scan for cla

**Comment by tetromino** [comment]
Fixed by #51 - and apologies for the year-long wait for review...

**Pull request closed without merging**
