### PR TITLE
Do not HTML-escape and use Markdown inline code for defaults

### LINKED ISSUE #137: Stardoc over-escapes angle brackets in docstrings.
Unfortunately, while https://github.com/bazelbuild/stardoc/pull/133 fixed a bunch of things, it also broke a bunch of other things.  In particular, if one has a rule or respository rule with a `doc` attribute like
```starlark
doc = """
Blah blah `<workspace_name>`
"""
```
it will be converted to
```markdown
Blah blah `&lt;workspace_name&gt;`
```
which renders as
> Blah blah `&lt;workspace_name&gt;`

The issue here, of course, is the mismatch between using HTML tags (e.g. `<pre>` or `<code>`) for formatting in some situations (e.g. tables), and native markdown formatting in others.  One must use escaping in the former situation, but using it in the latter breaks stuff.

### LINKED ISSUE #142: Stardoc outputs <code> blocks around attribute default values which aren't recognised by GitHub
rules_rust hosts its skydoc-generated documentation using GitHub Pages, e.g. at this URL: http://bazelbuild.github.io/rules_rust/crate_universe.html#repinning--updating-dependencies

We just had a bug report (https://github.com/bazelbuild/rules_rust/issues/1679) saying that quotes around the default values of attributes are fancy smart-quotes (`”`) rather than straight quotes (`"`), which means they can't be directly copied into starlark source.

It appears that this is because of the `<code>` block rendered by stardoc here: https://github.com/bazelbuild/stardoc/blob/6f274e903009158504a9d9130d7f7d5f3e9421ed/stardoc/templates/markdown_tables/func.vm#L18

As far as I can tell, GitHub doesn't recognise a `<code>` block at all. I can't find any details about it on any markdown references.

If instead we render the value in back-ticks, rather than a `<code>` block, GitHub will render these quotes verbatim.

While in general I'd view "your markdown renderer is incorrectly changing your content" as a user error, it feels like hosting docs on GitHub pages is probably the most likely form of hosting stardoc, GitHub-flavoured markdown should probably be a well-supported target of stardoc...

### PR DESCRIPTION
**Pull request by fmeum**
Reverts #133 so that HTML escaping is not applied to Markdown. Instead, Markdown content such as docstrings can use HTML formatting and escape angle brackets with backslashes, HTML entities or inline code segments. Default values are embedded in inline code segments instead of `<code>` tags, which does not require escaping.

As a result, docstrings behave just like regular Markdown contexts while default values are rendered without smart quotes and can contain both `<` and `` ` `` without causing escaping issues.

Also includes tests based on #138.

Fixes #137
Closes #138
Fixes #142
Closes #143

Requires https://github.com/bazelbuild/bazel/pull/18867

### CODE REVIEW

**Comment by fmeum** [comment]
@tetromino Could you review this PR? I created it when I noticed that updating Stardoc from `0.5.0` to `0.5.6` for Bzlmod compatibility broke my rulesets' docs (e.g. angle brackets in code blocks). I would really like to see Stardoc docs behave more similarly to other well-known Markdown contexts such as GitHub READMEs.

CC @illicitonion @adam-azarchs

**Comment by tetromino** [comment]
I agree with the PR in principle, but before reviewing and merging this, I want to move the markdown renderer java code here from the bazel repo and finally delete renderer_binary.jar instead of needing to keep updating it.

**Comment by fmeum** [comment]
Sounds good! I updated the PR to point to Bazel master and will happily make further changes post-move. Just mention me.

**Comment by fmeum** [comment]
@tetromino I rebased onto master including the move commit.

**Review by tetromino — APPROVED** [review]
Thanks, looks good. I do see an odd change with extra whitespace in some default values cells, but I think that can be fixed in a separate PR (we have bad whitespace discipline in general).

**Comment by fmeum** [comment]
@tetromino Thanks! It would be great if this could be included in a release soon to unblock rulesets that need to update for repo mapping support.

**Comment by tetromino** [comment]
> @tetromino Thanks! It would be great if this could be included in a release soon to unblock rulesets that need to update for repo mapping support.

This release will break all existing golden tests for Stardoc users. In order to minimize the frequency of such breakage, I want to additionally land the following breaking changes before cutting a release:

* support for starlark_doc_extract with Bazel HEAD (which will fix #123)
* multi-paragraph docstring dedenter - https://github.com/bazelbuild/bazel/pull/13403
* markdown table cell formatter - https://github.com/bazelbuild/bazel/pull/14230

**Pull request merged**
