### PR TITLE
Test Bzlmod support in CI

### LINKED ISSUE #110: On Windows, Stardoc inserts carriage return characters after processing each template
On Windows, Stardoc seems to insert a superfluous carriage return character in markdown output at the end of each processed template (*not* end of each line).

This means Stardoc's output on Windows is not byte-identical to the output Linux - which, among other things, prevents us from migrating to bazel-skylib's diff_test.

See the CI runs for https://github.com/bazelbuild/stardoc/commit/900f9f085699e79a17ba22ed0493b4163c1db82f which passed on Linux and macOS (https://buildkite.com/bazel/stardoc/builds/235#44e0a148-360c-48e3-aa07-215f796d5b7c) but failed on Windows (https://buildkite.com/bazel/stardoc/builds/235#6dc4c463-853d-47b3-8fee-9dffcdf30e2d).

### PR DESCRIPTION
**Pull request by fmeum**
Required updating the pinned Bazel commit and importing a patch to rules_jvm_external from the Bazel source tree.

Fixes #110

### CODE REVIEW

**Comment by fmeum** [comment]
@tetromino I sent out https://github.com/bazelbuild/bazel/pull/18327 to fix the issue uncovered by this test.

**Comment by fmeum** [comment]
I updated the Bazel pin and copied over a patch, now CI should pass even without https://github.com/bazelbuild/bazel/pull/18365. I am not sure whether the latter can be merged given the comments in the patch (bootstrap build).

@tetromino Could you create a release after the merge? I could add it to the BCR afterwards unless you want to take care of that.

**Review by tetromino — APPROVED** [review]
Thanks, looks good. I regenerated the jars on an internal machine.

**Comment by tetromino** [comment]
I accidentally failed to merge this before bumping the version number :/

Fortunately, we haven't cut the release yet.

**Pull request merged**
